a:5:{i:0;s:115:"SQLSTATE[HY000] [2002] Не можна здійснити підключення, оскільки кінцевий комп’ютер відхилив запит на підключення.
";i:1;s:1511:"#0 C:\web\htdocs\magento\lib\Zend\Db\Adapter\Pdo\Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 C:\web\htdocs\magento\lib\Varien\Db\Adapter\Pdo\Mysql.php(396): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 C:\web\htdocs\magento\lib\Zend\Db\Adapter\Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 C:\web\htdocs\magento\lib\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 C:\web\htdocs\magento\lib\Varien\Db\Adapter\Pdo\Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 C:\web\htdocs\magento\app\code\core\Mage\Core\Model\Resource.php(179): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 C:\web\htdocs\magento\app\code\core\Mage\Core\Model\Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#7 C:\web\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(141): Mage_Core_Model_Resource->getConnection('core_setup')
#8 C:\web\htdocs\magento\app\code\core\Mage\Core\Model\Resource\Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#9 C:\web\htdocs\magento\app\code\core\Mage\Core\Model\App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#10 C:\web\htdocs\magento\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Model_App->_initModules()
#11 C:\web\htdocs\magento\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#12 C:\web\htdocs\magento\index.php(83): Mage::run('', 'store')
#13 {main}";s:3:"url";s:14:"/magento/admin";s:11:"script_name";s:18:"/magento/index.php";s:4:"skin";s:7:"default";}